// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// SendWelcome provides a mock function with given fields: ctx, toEmail, name
func (_m *NotificationService) SendWelcome(ctx context.Context, toEmail string, name string) error {
	ret := _m.Called(ctx, toEmail, name)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcome")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, toEmail, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_SendWelcome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcome'
type NotificationService_SendWelcome_Call struct {
	*mock.Call
}

// SendWelcome is a helper method to define mock.On call
//   - ctx context.Context
//   - toEmail string
//   - name string
func (_e *NotificationService_Expecter) SendWelcome(ctx interface{}, toEmail interface{}, name interface{}) *NotificationService_SendWelcome_Call {
	return &NotificationService_SendWelcome_Call{Call: _e.mock.On("SendWelcome", ctx, toEmail, name)}
}

func (_c *NotificationService_SendWelcome_Call) Run(run func(ctx context.Context, toEmail string, name string)) *NotificationService_SendWelcome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationService_SendWelcome_Call) Return(_a0 error) *NotificationService_SendWelcome_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_SendWelcome_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationService_SendWelcome_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
