// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/example/myapp/internal/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// DomainEventPublisher is an autogenerated mock type for the DomainEventPublisher type
type DomainEventPublisher struct {
	mock.Mock
}

type DomainEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *DomainEventPublisher) EXPECT() *DomainEventPublisher_Expecter {
	return &DomainEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, events
func (_m *DomainEventPublisher) Publish(ctx context.Context, events ...domain.DomainEvent) error {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...domain.DomainEvent) error); ok {
		r0 = rf(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DomainEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type DomainEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...domain.DomainEvent
func (_e *DomainEventPublisher_Expecter) Publish(ctx interface{}, events ...interface{}) *DomainEventPublisher_Publish_Call {
	return &DomainEventPublisher_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *DomainEventPublisher_Publish_Call) Run(run func(ctx context.Context, events ...domain.DomainEvent)) *DomainEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]domain.DomainEvent, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(domain.DomainEvent)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *DomainEventPublisher_Publish_Call) Return(_a0 error) *DomainEventPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DomainEventPublisher_Publish_Call) RunAndReturn(run func(context.Context, ...domain.DomainEvent) error) *DomainEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewDomainEventPublisher creates a new instance of DomainEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDomainEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *DomainEventPublisher {
	mock := &DomainEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
