// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UnitOfWork is an autogenerated mock type for the UnitOfWork type
type UnitOfWork struct {
	mock.Mock
}

type UnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitOfWork) EXPECT() *UnitOfWork_Expecter {
	return &UnitOfWork_Expecter{mock: &_m.Mock}
}

// Within provides a mock function with given fields: ctx, fn
func (_m *UnitOfWork) Within(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Within")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnitOfWork_Within_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Within'
type UnitOfWork_Within_Call struct {
	*mock.Call
}

// Within is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *UnitOfWork_Expecter) Within(ctx interface{}, fn interface{}) *UnitOfWork_Within_Call {
	return &UnitOfWork_Within_Call{Call: _e.mock.On("Within", ctx, fn)}
}

func (_c *UnitOfWork_Within_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *UnitOfWork_Within_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *UnitOfWork_Within_Call) Return(_a0 error) *UnitOfWork_Within_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnitOfWork_Within_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *UnitOfWork_Within_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnitOfWork creates a new instance of UnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWork {
	mock := &UnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
