// Package openapi embeds this repo's OpenAPI specs so they can be served (e.g.
// at /openapi.json) without depending on the filesystem layout at runtime.
//
// myappv1.swagger.json is generated by `make proto` (buf + protoc-gen-openapiv2,
// with allow_merge so every REST-annotated proto's paths land in this one
// file — see buf.gen.yaml). It documents every context with a REST surface;
// each context's own .proto file is still the single source of truth for its
// slice of it, transcoded to REST by that context's own grpc-gateway mount
// (e.g. internal/customer/interfaces/grpc, internal/order/interfaces/grpc).
package openapi

import _ "embed"

//go:embed myappv1.swagger.json
var MyAppV1 []byte
