// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/example/myapp/internal/customer/application/dto"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/example/myapp/pkg/pagination"
)

// ReadModel is an autogenerated mock type for the ReadModel type
type ReadModel struct {
	mock.Mock
}

type ReadModel_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadModel) EXPECT() *ReadModel_Expecter {
	return &ReadModel_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ReadModel) GetByID(ctx context.Context, id string) (dto.Customer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.Customer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.Customer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadModel_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReadModel_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReadModel_Expecter) GetByID(ctx interface{}, id interface{}) *ReadModel_GetByID_Call {
	return &ReadModel_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ReadModel_GetByID_Call) Run(run func(ctx context.Context, id string)) *ReadModel_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReadModel_GetByID_Call) Return(_a0 dto.Customer, _a1 error) *ReadModel_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadModel_GetByID_Call) RunAndReturn(run func(context.Context, string) (dto.Customer, error)) *ReadModel_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page
func (_m *ReadModel) List(ctx context.Context, page pagination.Page) (pagination.Result[dto.Customer], error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 pagination.Result[dto.Customer]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Page) (pagination.Result[dto.Customer], error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Page) pagination.Result[dto.Customer]); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(pagination.Result[dto.Customer])
	}

	if rf, ok := ret.Get(1).(func(context.Context, pagination.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadModel_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ReadModel_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page pagination.Page
func (_e *ReadModel_Expecter) List(ctx interface{}, page interface{}) *ReadModel_List_Call {
	return &ReadModel_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *ReadModel_List_Call) Run(run func(ctx context.Context, page pagination.Page)) *ReadModel_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pagination.Page))
	})
	return _c
}

func (_c *ReadModel_List_Call) Return(_a0 pagination.Result[dto.Customer], _a1 error) *ReadModel_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadModel_List_Call) RunAndReturn(run func(context.Context, pagination.Page) (pagination.Result[dto.Customer], error)) *ReadModel_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewReadModel creates a new instance of ReadModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadModel {
	mock := &ReadModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
