// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	eventbus "github.com/example/myapp/internal/eventbus"
	mock "github.com/stretchr/testify/mock"

	outbox "github.com/example/myapp/internal/eventbus/outbox"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, events
func (_m *Store) Add(ctx context.Context, events ...eventbus.Event) error {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...eventbus.Event) error); ok {
		r0 = rf(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Store_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...eventbus.Event
func (_e *Store_Expecter) Add(ctx interface{}, events ...interface{}) *Store_Add_Call {
	return &Store_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *Store_Add_Call) Run(run func(ctx context.Context, events ...eventbus.Event)) *Store_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]eventbus.Event, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(eventbus.Event)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Store_Add_Call) Return(_a0 error) *Store_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Add_Call) RunAndReturn(run func(context.Context, ...eventbus.Event) error) *Store_Add_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPending provides a mock function with given fields: ctx, limit
func (_m *Store) FetchPending(ctx context.Context, limit int) ([]outbox.Message, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPending")
	}

	var r0 []outbox.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]outbox.Message, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []outbox.Message); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_FetchPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPending'
type Store_FetchPending_Call struct {
	*mock.Call
}

// FetchPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *Store_Expecter) FetchPending(ctx interface{}, limit interface{}) *Store_FetchPending_Call {
	return &Store_FetchPending_Call{Call: _e.mock.On("FetchPending", ctx, limit)}
}

func (_c *Store_FetchPending_Call) Run(run func(ctx context.Context, limit int)) *Store_FetchPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Store_FetchPending_Call) Return(_a0 []outbox.Message, _a1 error) *Store_FetchPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_FetchPending_Call) RunAndReturn(run func(context.Context, int) ([]outbox.Message, error)) *Store_FetchPending_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, eventID, reason
func (_m *Store) MarkFailed(ctx context.Context, eventID string, reason string) error {
	ret := _m.Called(ctx, eventID, reason)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, eventID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type Store_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - reason string
func (_e *Store_Expecter) MarkFailed(ctx interface{}, eventID interface{}, reason interface{}) *Store_MarkFailed_Call {
	return &Store_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, eventID, reason)}
}

func (_c *Store_MarkFailed_Call) Run(run func(ctx context.Context, eventID string, reason string)) *Store_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_MarkFailed_Call) Return(_a0 error) *Store_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkFailed_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, eventIDs
func (_m *Store) MarkPublished(ctx context.Context, eventIDs ...string) error {
	_va := make([]interface{}, len(eventIDs))
	for _i := range eventIDs {
		_va[_i] = eventIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, eventIDs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type Store_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - eventIDs ...string
func (_e *Store_Expecter) MarkPublished(ctx interface{}, eventIDs ...interface{}) *Store_MarkPublished_Call {
	return &Store_MarkPublished_Call{Call: _e.mock.On("MarkPublished",
		append([]interface{}{ctx}, eventIDs...)...)}
}

func (_c *Store_MarkPublished_Call) Run(run func(ctx context.Context, eventIDs ...string)) *Store_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Store_MarkPublished_Call) Return(_a0 error) *Store_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkPublished_Call) RunAndReturn(run func(context.Context, ...string) error) *Store_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
