// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	eventbus "github.com/example/myapp/internal/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

type Bus_Expecter struct {
	mock *mock.Mock
}

func (_m *Bus) EXPECT() *Bus_Expecter {
	return &Bus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, events
func (_m *Bus) Publish(ctx context.Context, events ...eventbus.Event) error {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...eventbus.Event) error); ok {
		r0 = rf(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Bus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Bus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...eventbus.Event
func (_e *Bus_Expecter) Publish(ctx interface{}, events ...interface{}) *Bus_Publish_Call {
	return &Bus_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *Bus_Publish_Call) Run(run func(ctx context.Context, events ...eventbus.Event)) *Bus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]eventbus.Event, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(eventbus.Event)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Bus_Publish_Call) Return(_a0 error) *Bus_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Bus_Publish_Call) RunAndReturn(run func(context.Context, ...eventbus.Event) error) *Bus_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: eventName, handler
func (_m *Bus) Subscribe(eventName string, handler eventbus.Handler) error {
	ret := _m.Called(eventName, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, eventbus.Handler) error); ok {
		r0 = rf(eventName, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Bus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Bus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - eventName string
//   - handler eventbus.Handler
func (_e *Bus_Expecter) Subscribe(eventName interface{}, handler interface{}) *Bus_Subscribe_Call {
	return &Bus_Subscribe_Call{Call: _e.mock.On("Subscribe", eventName, handler)}
}

func (_c *Bus_Subscribe_Call) Run(run func(eventName string, handler eventbus.Handler)) *Bus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(eventbus.Handler))
	})
	return _c
}

func (_c *Bus_Subscribe_Call) Return(_a0 error) *Bus_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Bus_Subscribe_Call) RunAndReturn(run func(string, eventbus.Handler) error) *Bus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus {
	mock := &Bus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
