// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	eventbus "github.com/example/myapp/internal/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

type Subscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *Subscriber) EXPECT() *Subscriber_Expecter {
	return &Subscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: eventName, handler
func (_m *Subscriber) Subscribe(eventName string, handler eventbus.Handler) error {
	ret := _m.Called(eventName, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, eventbus.Handler) error); ok {
		r0 = rf(eventName, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Subscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - eventName string
//   - handler eventbus.Handler
func (_e *Subscriber_Expecter) Subscribe(eventName interface{}, handler interface{}) *Subscriber_Subscribe_Call {
	return &Subscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", eventName, handler)}
}

func (_c *Subscriber_Subscribe_Call) Run(run func(eventName string, handler eventbus.Handler)) *Subscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(eventbus.Handler))
	})
	return _c
}

func (_c *Subscriber_Subscribe_Call) Return(_a0 error) *Subscriber_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Subscriber_Subscribe_Call) RunAndReturn(run func(string, eventbus.Handler) error) *Subscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
